name: Auto-create Issue

on:
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue
        uses: peter-evans/create-issue@v2
        with:
          title: '[ITEMID: ${{ github.run_id }}] Nouvelle issue'
          body: ''
          token: ${{ secrets.GITHUB_TOKEN }}
